### ISSUE TITLE
Logomark and logotype

### ISSUE THREAD

**Issue by zuurw** [DraciVik/Polaroid-Photo-Gallery#1]
Hello, how are you? Im a Graphic Designer that likes to contribute to open source projects. It would be a pleasure to work with you in this project, so if you need a logo I will do it for you..

Greetings.

**Comment by zuurw** [comment]
Hello @DraciVik  , Im going to close this issue, if you need my help with the logo you can reopen.
Best Regards.

**Comment by DraciVik** [comment]
@zuurw Thank you! I will have you in mind.

**Comment by zuurw** [comment]
Ok @DraciVik, if you need Im here to help, I have one logo that I design for this project, so if you want I can show you.

Greetings!

**Comment by zuurw** [comment]
Here are the 2 logos that I Design @DraciVik 
If you like one just say it.

![logo proposal polaroid2](https://user-images.githubusercontent.com/40801473/42507265-6f90e2e0-843c-11e8-860d-e7086e7342eb.png)
